spring:
  datasource:
    username: root
    password: "040027"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam1?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
##    static String dbURL = "jdbc:mysql://localhost:3306/"+"book"+"?useSSL=true&serverTimezone=UTC";
#    url: jdbc:mysql://localhost:3306/exam1?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
#    username: root

#    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver;
  web:
    resources:
      static-locations: classpath:/templates/
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: LEGACYHTML5
web:
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/templates/, classpath:/public/
server:
  port: 8081
mybatis:
  configuration:
    call-setters-on-nulls: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
